export const CATEGORIES = {
  ShoppingMalls: 'shopping-malls',
  CoffeeShops: 'coffee-shops',
  CarWashes: 'car-washes',
  MovieTheaters: 'movie-theaters',
  HotelsVacationRentals: 'hotels-vacation-rentals',
  CityCounselPublicLocations: 'city-counsel-public-locations',
  RestaurantBars: 'restaurant-bars',
  ChainStores: 'chain-stores',
  BillboardOwners: 'billboard-owners',
  StadiumsArenas: 'stadiums-arenas',
  CommercialKitchens: 'commercial-kitchens',
  EventVenueOwners: 'event-venue-owners',
  Landlords: 'landlords',
  IndustrialParkOwners: 'industrial-park-owners',
  CommercialRealEstateOfficeBuildingOwners:
    'commercial-real-estate-office-building-owners',
  Airports: 'airports',
  TrainStations: 'train-stations',
  ShoppingCenterStripMall: 'shopping-center-strip-mall',
  GroceryStores: 'grocery-stores',
  BusinessIncubatorCollaborativeWorkspaces:
    'business-incubator-collaborative-workspaces',
  HospitalHealthcare: 'hospital-healthcare',
  CommunityCenters: 'community-centers',
  CarDealerships: 'car-dealerships',
  UniversitiesCollegesSchools: 'universities-colleges-schools',
  VacantLotOwners: 'vacant-lot-owners',
  Churches: 'churches',
  WarehousesStorageSpace: 'warehouses-storage-space',
  ParkingGarages: 'parking-garages',
  Libraries: 'libraries',
  HistoricBuildings: 'historic-buildings',
};
