export const USE_CASES = {
  VendingMachine: 'vending-machine',
  ATM: 'atm',
  Advertisement: 'advertisement',
  ProductPlacement: 'product-placement',
  FoodTrucks: 'food-trucks',
  Events: 'events',
  ClassesEducatorsInstructors: 'classes-educators-instructors',
  PopUpShops: 'pop-up-shops',
  ArtistsArtisanFashion: 'artists-artisan-fashion',
  TechStartUpsCoworking: 'tech-start-ups-coworking',
  RealEstate: 'real-estate',
  InteriorDesigners: 'interior-designers',
  PerformerEntertainers: 'performer-entertainers',
  NonProfitCharities: 'non-profit-charities',
  LocalFarmersProduceVendors: 'local-farmers-produce-vendors',
  EntrepreneursSmallBusinesses: 'entrepreneurs-small-businesses',
  ProfessionalServiceProviders: 'professional-service-providers',
};
